### ISSUE TITLE
wildfly-arquillian-container-domain-managed : Deployment with Servlet Protocol not possible

### ISSUE THREAD

**Issue by weand** [wildfly/wildfly-arquillian#46] opened 2015-10-07 22:00 UTC
Currently its not possible to run _container-domain-managed_ tests with wildfly (full) using Arquillian Servlet Protocol. See this [project](https://github.com/catandgrep/wildfly-arquillian-domain-managed-testing) for how to reproduce and further details.

Is this a known limitation right now?

**Comment by jamezp** [comment] 2015-10-07 22:34
Thank you very much for the reproducer. I think the issue is related to https://issues.jboss.org/browse/WFCORE-988. If that's the cause we'll have to wait until we can upgrade the plugin to use WildFly Core 2.x. We'll likely have to switch to a wildfly-arquillian 2.x for the master branch since it will require an upgrade to Java 8.

**Comment by catandgrep** [comment] 2015-10-08 08:05
I can confirm that the issue is related to WFCORE-988.

The workaround is disabling assertions in arquillian xml.
```
<arquillian>

  ...

  <container qualifier="jboss" default="true">
    ...
    <property name="enableAssertions">false</property>
    ...
  </container>

</arquillian>
```

How about setting enabledAssertions to false by default. Right now its true:
```
org.jboss.as.arquillian.container.domain.managed.ManagedDomainContainerConfiguration.enableAssertions = true
```

**Comment by jamezp** [comment] 2015-10-08 20:32
We could, but it just seems odd to have assertions disabled for tests. Though it does seem odd to have it enabled if it doesn't work.

**Comment by feskehau** [comment] 2017-02-09 20:51
Was there any fix on this?

**Comment by jamezp** [comment] 2017-02-10 00:22
I think it should work in WildFly 10. I'll wait to close this until I get a chance to verify that though.

**Comment by jamezp** [comment] 2020-02-03 19:21
This seems to be fixed so I'm closing this.

**Closed by jamezp** 2020-02-03 19:21 UTC
