### ISSUE TITLE
Cannot run tests: java.lang.NoSuchMethodError: ....setAuthenticationConfigUri...

### ISSUE THREAD

**Issue by linex83** [wildfly/wildfly-arquillian#115] opened 2017-11-22 20:25 UTC
I am trying to run my integration tests with WildFly. My tests have been working perfectly with GlassFish4, but with WildFly I get the following exception when running my tests:

```
java.lang.NoSuchMethodError: org.jboss.as.controller.client.ModelControllerClientConfiguration$Builder.setAuthenticationConfigUri(Ljava/net/URI;)Lorg/jboss/as/controller/client/ModelControllerClientConfiguration$Builder;
	at org.jboss.as.arquillian.container.CommonDeployableContainer.start(CommonDeployableContainer.java:104)
	at org.jboss.arquillian.container.impl.ContainerImpl.start(ContainerImpl.java:199)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:163)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:157)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:255)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startContainer(ContainerLifecycleController.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:92)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$2.perform(ContainerLifecycleController.java:77)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$2.perform(ContainerLifecycleController.java:70)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forEachSuiteContainer(ContainerLifecycleController.java:221)
	at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startSuiteContainers(ContainerLifecycleController.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:92)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:116)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
```

Here is my pom.xml:

```
<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.2</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.20.1</version>
      </plugin>
    </plugins>
  </build>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.jboss.arquillian</groupId>
        <artifactId>arquillian-bom</artifactId>
        <version>1.1.13.Final</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.junit</groupId>
      <artifactId>arquillian-junit-container</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>


  <profiles>
    <profile>
      <id>arquillian-wildfly-managed</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <dependencies>
        <dependency>
          <groupId>org.wildfly.arquillian</groupId>
          <artifactId>wildfly-arquillian-container-managed</artifactId>
          <version>2.1.0.Final</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.20.1</version>
            <configuration>
              <systemPropertyVariables>
                <arquillian.launch>wildfly8-managed</arquillian.launch>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
              </systemPropertyVariables>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```

I'm out of ideas how to approach this problem. Seems to me like it's a dependency issue within wildfly-arquillian-container-managed. Please let me know if you need further information.

**Comment by jamezp** [comment] 2017-11-22 21:11
What is your target version of WildFly?

**Comment by linex83** [comment] 2017-11-22 21:12
I tried 8.1.0.Final and 10.1.0.Final.

**Comment by jamezp** [comment] 2017-11-22 21:16
It looks like an older version of the `org.wildfly.core:wildfly-controller-client` is being used. Do you by chance have a dependency on that? If not could you do a `mvn dependency:tree` and paste the results?

**Comment by linex83** [comment] 2017-11-22 21:24
```
[INFO] aput:aput.web.arq.wild:war:0.0.1-SNAPSHOT
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.jboss.arquillian.junit:arquillian-junit-container:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.junit:arquillian-junit-core:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.test:arquillian-test-api:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.test:arquillian-test-spi:jar:1.1.13.Final:test
[INFO] |  |  \- org.jboss.arquillian.core:arquillian-core-spi:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-test-api:jar:1.1.13.Final:test
[INFO] |  |  \- org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-test-spi:jar:1.1.13.Final:test
[INFO] |  |  \- org.jboss.arquillian.container:arquillian-container-spi:jar:1.1.13.Final:test
[INFO] |  |     \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-base:jar:2.0.0-alpha-10:test
[INFO] |  +- org.jboss.arquillian.core:arquillian-core-impl-base:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.test:arquillian-test-impl-base:jar:1.1.13.Final:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-impl-base:jar:1.1.13.Final:test
[INFO] |  |  +- org.jboss.arquillian.config:arquillian-config-api:jar:1.1.13.Final:test
[INFO] |  |  +- org.jboss.arquillian.config:arquillian-config-impl-base:jar:1.1.13.Final:test
[INFO] |  |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-spi:jar:2.0.0-alpha-10:test
[INFO] |  +- org.jboss.arquillian.container:arquillian-container-test-impl-base:jar:1.1.13.Final:test
[INFO] |  \- org.jboss.shrinkwrap:shrinkwrap-impl-base:jar:1.2.6:test
[INFO] |     \- org.jboss.shrinkwrap:shrinkwrap-spi:jar:1.2.6:test
[INFO] \- org.wildfly.arquillian:wildfly-arquillian-container-managed:jar:2.1.0.Final:test
[INFO]    +- org.wildfly.arquillian:wildfly-arquillian-common:jar:2.1.0.Final:test
[INFO]    |  +- org.jboss.arquillian.testenricher:arquillian-testenricher-cdi:jar:1.1.13.Final:test
[INFO]    |  +- org.jboss.arquillian.testenricher:arquillian-testenricher-ejb:jar:1.1.13.Final:test
[INFO]    |  +- org.jboss.arquillian.testenricher:arquillian-testenricher-initialcontext:jar:1.1.13.Final:test
[INFO]    |  +- org.jboss.arquillian.testenricher:arquillian-testenricher-resource:jar:1.1.13.Final:test
[INFO]    |  +- org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar:1.1.13.Final:test
[INFO]    |  +- org.wildfly.arquillian:wildfly-arquillian-testenricher-msc:jar:2.1.0.Final:test
[INFO]    |  |  \- org.wildfly.core:wildfly-server:jar:3.0.0.Final:test
[INFO]    |  |     +- org.wildfly.core:wildfly-controller:jar:3.0.0.Final:test
[INFO]    |  |     |  +- org.jboss:staxmapper:jar:1.3.0.Final:test
[INFO]    |  |     |  \- org.projectodd.vdx:vdx-wildfly:jar:1.1.6:test
[INFO]    |  |     |     \- org.projectodd.vdx:vdx-core:jar:1.1.6:test
[INFO]    |  |     +- org.wildfly.core:wildfly-core-management-client:jar:3.0.0.Final:test
[INFO]    |  |     +- org.wildfly.core:wildfly-domain-http-interface:jar:3.0.0.Final:test
[INFO]    |  |     |  \- org.wildfly.security.elytron-web:undertow-server:jar:1.0.0.Final:test
[INFO]    |  |     +- org.wildfly.core:wildfly-deployment-repository:jar:3.0.0.Final:test
[INFO]    |  |     +- org.wildfly.core:wildfly-platform-mbean:jar:3.0.0.Final:test
[INFO]    |  |     +- org.wildfly.core:wildfly-process-controller:jar:3.0.0.Final:test
[INFO]    |  |     +- org.wildfly.core:wildfly-network:jar:3.0.0.Final:test
[INFO]    |  |     +- org.wildfly.core:wildfly-version:jar:3.0.0.Final:test
[INFO]    |  |     +- org.jboss:jandex:jar:2.0.3.Final:test
[INFO]    |  |     +- org.jboss.invocation:jboss-invocation:jar:1.5.0.Final:test
[INFO]    |  |     +- org.jboss.logmanager:jboss-logmanager:jar:2.0.7.Final:test
[INFO]    |  |     +- org.jboss.modules:jboss-modules:jar:1.6.0.Final:test
[INFO]    |  |     +- org.jboss.stdio:jboss-stdio:jar:1.0.2.GA:test
[INFO]    |  |     +- org.jboss:jboss-vfs:jar:3.2.12.Final:test
[INFO]    |  |     \- io.undertow:undertow-core:jar:1.4.18.Final:test
[INFO]    |  +- org.wildfly.core:wildfly-controller-client:jar:3.0.0.Final:test
[INFO]    |  |  +- org.wildfly.core:wildfly-protocol:jar:3.0.0.Final:test
[INFO]    |  |  +- org.jboss:jboss-dmr:jar:1.4.1.Final:test
[INFO]    |  |  \- org.jboss.threads:jboss-threads:jar:2.2.1.Final:test
[INFO]    |  +- org.wildfly.plugins:wildfly-plugin-core:jar:1.2.0.Final:test
[INFO]    |  +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-base:jar:2.0.0-alpha-10:test
[INFO]    |  \- org.wildfly.common:wildfly-common:jar:1.2.0.Final:test
[INFO]    +- org.wildfly.arquillian:wildfly-arquillian-protocol-jmx:jar:2.1.0.Final:test
[INFO]    |  +- org.wildfly.security:wildfly-elytron:jar:1.1.0.Final:test
[INFO]    |  +- org.jboss.arquillian.protocol:arquillian-protocol-jmx:jar:1.1.13.Final:test
[INFO]    |  \- org.wildfly.core:wildfly-jmx:jar:3.0.0.Final:test
[INFO]    |     +- org.jboss.msc:jboss-msc:jar:1.2.7.SP1:test
[INFO]    |     \- org.wildfly.core:wildfly-remoting:jar:3.0.0.Final:test
[INFO]    |        +- org.wildfly.core:wildfly-domain-management:jar:3.0.0.Final:test
[INFO]    |        |  +- org.picketbox:picketbox:jar:5.0.2.Final:test
[INFO]    |        |  \- org.wildfly.openssl:wildfly-openssl-java:jar:1.0.2.Final:test
[INFO]    |        +- org.wildfly.core:wildfly-core-security:jar:3.0.0.Final:test
[INFO]    |        |  \- org.wildfly.core:wildfly-core-security-api:jar:3.0.0.Final:test
[INFO]    |        \- org.wildfly.core:wildfly-io:jar:3.0.0.Final:test
[INFO]    +- org.jboss.xnio:xnio-api:jar:3.5.1.Final:test
[INFO]    |  \- org.wildfly.client:wildfly-client-config:jar:1.0.0.Final:test
[INFO]    +- org.jboss.xnio:xnio-nio:jar:3.5.1.Final:test
[INFO]    +- org.jboss.logging:jboss-logging:jar:3.3.1.Final:test
[INFO]    +- org.jboss.marshalling:jboss-marshalling:jar:2.0.0.Final:test
[INFO]    +- org.jboss.marshalling:jboss-marshalling-river:jar:2.0.0.Final:test
[INFO]    +- org.jboss.remoting:jboss-remoting:jar:5.0.0.Final:test
[INFO]    +- org.jboss.remotingjmx:remoting-jmx:jar:3.0.0.Final:test
[INFO]    +- javax.inject:javax.inject:jar:1:test
[INFO]    +- org.wildfly.core:wildfly-launcher:jar:3.0.0.Final:test
[INFO]    \- org.jboss.arquillian.core:arquillian-core-api:jar:1.1.13.Final:test
```

**Comment by jamezp** [comment] 2017-11-22 21:28
That all looks correct. I can't seem to reproduce this either. You don't by chance have some kind of reproducer do you?

As a workaround you could use 2.0.2.Final which won't be attempting to use the missing setter.

**Comment by linex83** [comment] 2017-11-22 21:45
Thank you so much for your help thus far! It really does work with 2.0.2.Final. However, I would like to find out how to make it work with more current versions, as it might help other people as well. Could you try to make my project run? I tried to keep it minimal:

[rscbundle.zip](https://github.com/wildfly/wildfly-arquillian/files/1497551/rscbundle.zip)

**Comment by linex83** [comment] 2017-11-23 12:42
It does indeed work if I run it from the console. I've been running it from eclipse previously, leading to the error mentioned above. I haven't figured out how to fix this yet, but I now know it's not an arquillian / wildfly issue.

Thank you very much for your help! I'm looking forward to work with arquillian / wildfly.

**Comment by jamezp** [comment] 2017-11-28 18:02
Not a problem. I'll close this for now.

**Closed by jamezp** 2017-11-28 18:02 UTC
